### ISSUE TITLE
Attributes of type ENUMs:  Forms are not created correctly (no drop-down lists or similar)  because of missing relations or other reasons

### ISSUE THREAD

**Issue by pramisters** [opengisch/projectgenerator#119] opened 2017-12-13 16:22 UTC
If an attribute with ENUM type is defined in an abstract class, projectgenerator doesn't create a relation in QGIS although the ENUM table is marked as "ENUM" in the metadatatable t_ili2db_table_prop.

Therefore, the widget type in the form Definition is not defined as "Relation reference", but "Text Edit".

In the attached example the abstract class "Hecken_Feldgehoelze_Basis" (with several attributes of type "ENUM") is extended to the classes "Hecken_Feldgehoelze_Linie" and "Hecken_Feldgehoelze_Flaeche" where the QGIS relation definitions to the ENUM tables are missing.

[ZG_Hecken_und_Feldgehoelze_V1_0.txt](https://github.com/opengisch/projectgenerator/files/1556215/ZG_Hecken_und_Feldgehoelze_V1_0.txt)

**Comment by gacarrillor** [comment] 2017-12-16 02:00
Could you please confirm if this happens in Project Generator v2.0.0?

**Comment by pramisters** [comment] 2017-12-18 13:31
Yes, it works now for ENUM type attributes in ABSTRACT classes! Thanks!

But there is another case where the QGIS relations are missing (although the entries in the t_ili2db_table_prop are present): 
**If ENUMs are defined inline (directly within the CLASS Definition)** 

Try the attached ili-model "Abfallsammelstellen_ZEBA_LV95_V1". For the Inline-ENUMs
- Abfallsammelstellen.Eigentum
- Abfallsammelstellen.Grundeigentum
- Abfallsammelstellen.OeffentlicheSammelstelle

the QGIS relations are missing, although the corresponding entries in t_ili2db_table_prop are present.

[ZG_Abfallsammelstellen_ZEBA_V1.txt](https://github.com/opengisch/projectgenerator/files/1568055/ZG_Abfallsammelstellen_ZEBA_V1.txt)

**Comment by m-kuhn** [comment] 2017-12-18 13:42
Is this a duplicate of 
https://github.com/opengisch/projectgenerator/issues/96 ?

**Comment by pramisters** [comment] 2017-12-18 13:51
Kind of, yes.
#96 was related to the missing foreign key. Now the implementation is different (work around with t_ili2db_table_prop). From my point of view, #96 can be closed as it has been replaced by this issue.

**Comment by pramisters** [comment] 2018-03-27 16:25
The issue persists:
[ZG_Naturschutz_und_Erholung_V1_0.txt](https://github.com/opengisch/projectgenerator/files/1852835/ZG_Naturschutz_und_Erholung_V1_0.txt)

In the attached example only one of 1 of 8 relations in QGIS for ENUM tables are generated although entries in t_ili2db_table_prop are present.

![t_ili2db_table_prop](https://user-images.githubusercontent.com/23503534/37980730-500b44dc-31db-11e8-82a6-6d8630574ba3.png)

**Comment by pramisters** [comment] 2018-03-27 16:29
The Problem persists:
[ZG_Naturschutz_und_Erholung_V1_0.txt](https://github.com/opengisch/projectgenerator/files/1852865/ZG_Naturschutz_und_Erholung_V1_0.txt)

In the attached model example only 1 of 8 relations are generated although all entries in t_ili2db_table_prop are present:

![t_ili2db_table_prop](https://user-images.githubusercontent.com/23503534/37980914-c9c9bf10-31db-11e8-8cd2-c80aaf5f1fc1.png)

**Comment by gacarrillor** [comment] 2018-04-12 16:26
@pramisters The issue with domains for structures should be fixed in Project Generator v3.0.5, could you please confirm?

**Comment by pramisters** [comment] 2018-04-16 16:07
Some more models tested:

1. [Hazard_Mapping_V1_2.txt](https://github.com/opengisch/projectgenerator/files/1916015/Hazard_Mapping_V1_2.txt)
--> No relations for ENUMs are created although t_ili2db_table_prop is correctly populated
The ENUMs are all defined as (FINAL). Could that be the problem here?

2.  [ZG_Hazard_Mapping_V1_2.txt](https://github.com/opengisch/projectgenerator/files/1916181/ZG_Hazard_Mapping_V1_2.txt)
--> Model Extension of 1.
--> Same result as 1.: No relations for ENUMs

3. [Waldgrenzen_V1_1.txt](https://github.com/opengisch/projectgenerator/files/1916122/Waldgrenzen_V1_1.txt)
--> OK !

4. [ZG_Abfallsammelstellen_ZEBA_V1.txt](https://github.com/opengisch/projectgenerator/files/1916171/ZG_Abfallsammelstellen_ZEBA_V1.txt) (Abfallsammelstellen_ZEBA_LV95_V1) 
--> See description above
--> If ENUMs are defined inline, no relations are generated by the Project Generator

**Comment by gacarrillor** [comment] 2018-05-07 11:00
Work in progress:

1. Hazard_Mapping_V1_2.txt: Solved in 4bc8c8e.

**Comment by pramisters** [comment] 2018-05-22 09:06
After some testing:

1. QGIS relations are generated correctly (in my examples from above) except for the case of KbS_LV95_V1_3 mentioned by @romefi. The difference to the other examples here is, that the ENUM definitions (DOMAIN and STRUCTURE) are in a seperate model (KbS_Basis_V1_3).

2.  Forms: When ENUMs are combined with BAG OF the widget type "list" makes no sense and is not usable. Currently the only available widget that can handle multiple selections is the "value relation" widget. --> #171

**Comment by gacarrillor** [comment] 2018-07-30 22:15
The remaining issue reported by @romefi (`Untersuchungsmassnahmen` and `Deponietyp` in  `KbS_LV95_V1_3` model) should be fixed with commit https://github.com/opengisch/projectgenerator/pull/227/commits/7dd5a90e6b837b6400d03f53eff2920adaff76c5  See:

![untersmassn](https://user-images.githubusercontent.com/652785/43426641-03872fec-941c-11e8-9ba7-87bef4ae8e47.png)


Please confirm, so that we can finally close this issue.

@pramisters The two issues you listed in your latest comment should be solved now with PR #227

**Comment by m-kuhn** [comment] 2018-07-31 07:36
Thanks a lot for this @gacarrillor !!!!

@pramisters / @romefi do we ship the additional metaattribute in an interlis plus file or do we upstream it to the repository?

**Closed** 2018-08-11 06:35 UTC
