### ISSUE TITLE
Add option --importTid (column t_ili_tid)

### ISSUE THREAD

**Issue by romefi** [opengisch/projectgenerator#204] opened 2018-06-05 09:19 UTC
Had some trouble with model [ExceptionalLoadsRoute_LV95_V1 ](http://models.geo.admin.ch/ASTRA/ExceptionalLoadsRoute_V1.ili). The [catalogue](http://models.geo.admin.ch/ASTRA/ExceptionalLoadsRoute_Catalogue_V1.xml) contains a TID for every object. This TID has to be stored, it's used for the export of data by ili2db to refer the collected data to the TID. Otherwise the xtf has errors. The TID can be generated and imported with the option --importTid. 
With this option, a new column named "t_ili_tid" is generated. This column gets also generated without the option --importTid, if the TID is an OID.
As far as I see, it's only relevant for the import or export of data. But also needed when created schema if a catalogue is imported later. We could add this option and handle the visibility of "t_ili_tid" as defined in https://github.com/opengisch/projectgenerator/issues/1. If someone sees a problem, I'm open for discussion :)

**Comment by m-kuhn** [comment] 2018-06-05 09:23
Duplicate of https://github.com/opengisch/projectgenerator/issues/127

**Closed by m-kuhn** 2018-06-05 09:23 UTC

**Comment by claeis** [comment] 2018-08-15 22:07
The mentioned model is wrong. The references to the catalog should be based on stable OIDs, which would trigger the creation of the t_ili_tid column which would allow ili2db to resolve the reference.

```--importTid``` hurts, because t_ili_tid appears on every mask/dialog.

see also claeis/ili2db#207
